// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.commentTrendingStmt, err = db.PrepareContext(ctx, commentTrending); err != nil {
		return nil, fmt.Errorf("error preparing query CommentTrending: %w", err)
	}
	if q.deleteExpiredTokensStmt, err = db.PrepareContext(ctx, deleteExpiredTokens); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredTokens: %w", err)
	}
	if q.insertTrendingStmt, err = db.PrepareContext(ctx, insertTrending); err != nil {
		return nil, fmt.Errorf("error preparing query InsertTrending: %w", err)
	}
	if q.likeTrendingStmt, err = db.PrepareContext(ctx, likeTrending); err != nil {
		return nil, fmt.Errorf("error preparing query LikeTrending: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.commentTrendingStmt != nil {
		if cerr := q.commentTrendingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing commentTrendingStmt: %w", cerr)
		}
	}
	if q.deleteExpiredTokensStmt != nil {
		if cerr := q.deleteExpiredTokensStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredTokensStmt: %w", cerr)
		}
	}
	if q.insertTrendingStmt != nil {
		if cerr := q.insertTrendingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertTrendingStmt: %w", cerr)
		}
	}
	if q.likeTrendingStmt != nil {
		if cerr := q.likeTrendingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing likeTrendingStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                      DBTX
	tx                      *sql.Tx
	commentTrendingStmt     *sql.Stmt
	deleteExpiredTokensStmt *sql.Stmt
	insertTrendingStmt      *sql.Stmt
	likeTrendingStmt        *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                      tx,
		tx:                      tx,
		commentTrendingStmt:     q.commentTrendingStmt,
		deleteExpiredTokensStmt: q.deleteExpiredTokensStmt,
		insertTrendingStmt:      q.insertTrendingStmt,
		likeTrendingStmt:        q.likeTrendingStmt,
	}
}
