// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: feedback.sql

package db

import (
	"context"

	null "gopkg.in/guregu/null.v4"
)

const getFeedback = `-- name: GetFeedback :many
SELECT feedback_id,user_id,image_uri,content,created_at,status,comment from feedback
`

func (q *Queries) GetFeedback(ctx context.Context) ([]*Feedback, error) {
	rows, err := q.query(ctx, q.getFeedbackStmt, getFeedback)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Feedback{}
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.FeedbackID,
			&i.UserID,
			&i.ImageUri,
			&i.Content,
			&i.CreatedAt,
			&i.Status,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComments = `-- name: UpdateComments :exec
UPDATE feedback SET status = (?),comment = (?)
WHERE feedback_id = (?)
`

type UpdateCommentsParams struct {
	Status     bool        `json:"status"`
	Comment    null.String `json:"comment"`
	FeedbackID int64       `json:"feedback_id"`
}

func (q *Queries) UpdateComments(ctx context.Context, arg UpdateCommentsParams) error {
	_, err := q.exec(ctx, q.updateCommentsStmt, updateComments, arg.Status, arg.Comment, arg.FeedbackID)
	return err
}
