// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: feedback.sql

package db

import (
	"context"
)

const getFeedback = `-- name: GetFeedback :many
SELECT feedback_id, user_id, image_uri, content from feedback
`

func (q *Queries) GetFeedback(ctx context.Context) ([]*Feedback, error) {
	rows, err := q.query(ctx, q.getFeedbackStmt, getFeedback)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Feedback{}
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.FeedbackID,
			&i.UserID,
			&i.ImageUri,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
