// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	CommentTrending(ctx context.Context) ([]*CommentTrendingRow, error)
	CommentTrendingUsers(ctx context.Context) ([]*CommentTrendingUsersRow, error)
	DeleteExpiredTokens(ctx context.Context) error
	InsertTrending(ctx context.Context, postID int64) error
	InsertTrendingUsers(ctx context.Context, userID int32) error
	LikeTrending(ctx context.Context) ([]*LikeTrendingRow, error)
	LikeTrendingUsers(ctx context.Context) ([]*LikeTrendingUsersRow, error)
}

var _ Querier = (*Queries)(nil)
