// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: token.sql

package db

import (
	"context"
)

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM token WHERE CURRENT_TIMESTAMP(3) > expired_at
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteExpiredTokensStmt, deleteExpiredTokens)
	return err
}
